### ISSUE TITLE
Speco Camera won't connect

### ISSUE THREAD

**Issue by burt-macklin1** [SvenVD/rpisurv#105]
Hello, ive been using this for a while and im setting one up at work now and we use Speco cameras. I can get the stream up in VLC using rtsp://<User>:<Password>@<IP>:554/ (i removed user name and password, But its filled out) but the Pi just sits on Connecting.  Not sure why VLC connects but the Pi cant. Hopefully im just missing something easy.

![Capture](https://user-images.githubusercontent.com/44486418/96625324-a32d8180-12d3-11eb-93c3-d34a8cfb2186.PNG)

**Comment by SvenVD** [comment]
Hi,

It is advised to use the community.rpisurv.net/ for support.  

To be able to troubleshoot, you should provide following information:
https://www.tapatalk.com/groups/rpisurv/guidelines-t13.html

If you could give the most recent logs of /var/log/daemon.log and /usr/local/bin/rpisurv/logs/main.log we probably can already see what is wrong.

Thanks

**Comment by burt-macklin1** [comment]
When im at work ill grab that log, and i can open a ticket over there if that is easier

**Comment by burt-macklin1** [comment]
[main.log](https://github.com/SvenVD/rpisurv/files/5423601/main.log)

**Comment by SvenVD** [comment]
Ok I see that omxplayer is crashing, rpisurv detects this and tries to restart the stream however it fails because omxplayer keeps on crashing.

Omxplayer does not mention why it is crashing. So we would have to guess, what is codec and the resolution of your camerastream, maybe try with a substream and make sure basic h.264 is selected. You have to do some trial and error with different resolutions and codec setting for your camerastream to test why omxplayer does not like the current stream presented to it

Please do note that your passwords seem to be in the debug log, because for some reason the core worker logs also appear in your main.log
